<script type="text/javascript">

el = '.super-attribute-select';

$$(el).each(function(select_element) {
    var stored_el_val = getCookie(select_element.id);
    SetSelect(select_element.id, stored_el_val)
});


function SetSelect(el, stored_el_val) {
    option_el = "#" + el + " option[value="+stored_el_val+"]";
    if ($(el) && ($$(option_el).length > 0)) {
        try {
            $(el).value = stored_el_val;
            $(el).simulate('change');
        } 
        catch (e) { 
        }
    }
}

function Setstored_el_val(obj) {
    if (obj.value && obj.value) {
        setCookie(obj.id, obj.value);
    }
}


$$(el).each(function(select) {
    Event.observe(select, 'change', function() { Setstored_el_val($(this)) });
});

function ValidateSelectValue(el, val_to_check) {
  var exists = false;
  $$(el).each(function(select){
    if(select.value == val_to_check)
    {
        alert(select.value + val_to_check);
        exists = true;
        throw $break;
     }
  });
  return exists;
}

function setCookie(cname, cvalue) {
    var d = new Date();
    var exdays = 365;
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires="+d.toUTCString();
    document.cookie = cname + "=" + cvalue + "; " + expires;
}

function getCookie(cname) {
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for(var i=0; i<ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1);
        if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
    }
    return "";
}

</script>